package com.json_parser;

public enum TokenType {
    // STRING RELATED TOKENS
    STRING, TRUE, FALSE, NUMBER, NULL,

    // SYNTAX RELATED TOKENS
    COMMA, COLON, EOF,

    // NESTED OBJECTS
    LBRACKET, RBRACKET, LPARENTHESIS, RPARENTHESIS, LBRACE, RBRACE
}
